server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://centerbeam.proxy.rlwy.net:59127/railway}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

app:
  callback-base-url: ${APP_CALLBACK_BASE_URL:http://localhost:8080}
  frontend-return-url: ${APP_FRONTEND_RETURN_URL:http://localhost:3000}
  jwt-secret: ${APP_JWT_SECRET:my-local-dev-secret-12345678901234567890}
  jwt-expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}

firebase:
  database-url: ${FIREBASE_DATABASE_URL}

kora:
  secret-key: ${KORA_SECRET_KEY}
  base-url: ${KORA_BASE_URL:https://api.korapay.com}