#spring.application.name=dashboard
server:
  port: 8080

spring:
  datasource:
    url: mysql://root:Jaykip@123@centerbeam.proxy.rlwy.net:31360/betting_app_tips_db
    username: root
    password: Jaykip@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false